### ISSUE TITLE
Cannot ssh into server after install on Hetzner ROBOT

### ISSUE THREAD

**Issue by timthelion** [numtide/nixos-anywhere#110]
**Describe the bug**

I tried installing using the config listed here (which is as close as I could get to the config in the README while updating things to fit current disco and the hetzner disk config): https://github.com/timthelion/server-configs-la/blob/b89eded82217e70bbe1a43a7da30a5a88d960975/nixos/INSTALL_LOG2.txt#LL1C1-L1C1

Install seems to run without error but then I cannot ssh into the server after it completes.

**To Reproduce**

1. Create a Hetzner robot server. 
2. Reboot into the recovery.
3. Clone repo above.
4. Run command `nix --extra-experimental-features flakes --extra-experimental-features nix-command run github:numtide/nixos-any
where -- --flake .#hetzner-cloud root@monitor.bitswan.space`
5. Wait a bit and try sshing into the server
6. Reboot the system using the hetzner admin
6.  Wait a bit and try sshing into the server

**Expected behavior**

Sshing into the system after install works

**Actual behavior**

Ssh hangs

**Comment by Mic92** [comment]
You are probably missing kernel modules: https://github.com/numtide/srvos/blob/9e172d6cd8afffef25e46208df88a2946f1f8f0d/nixos/hardware/hetzner-online/default.nix#L18
