### ISSUE TITLE
How can I continue to use/update the same configuration post install

### ISSUE THREAD

**Issue by timthelion** [numtide/nixos-anywhere#118]
The installation leaves me with a nix system but no configuration.nix or hardware-configuration.nix. What is the best way to create these files and keep them in sync with the original flake? I'd like to be able to have a "working configuration" of the server that I can restore at any time.

**Comment by phaer** [comment]
That depends a bit on how you got the config you've installed in the first place. You can pass nixos-anywhere either a flake attribute or a store path, both representing a nixos configuration. 

If it's just a store path, the question is how did you get that store path?
If it's a flake attribute you can just use e.g. `nixos-rebuild switch ./my-flake#nixosConfigurations.my-config` to update on the target host itself, or `nixos-rebuild` with `--target-host` or even an external tool like e.g. colmena.cli.rs to deploy from your local machine to the target.

**Comment by timthelion** [comment]
Thanks. So what is the difference between nix-os-anywhere and nixos-rebuild switch? Don't they both just create files in the `/nix` directory and install a bootloader as configured?

**Comment by timthelion** [comment]
This seems to work just fine. Only I had to use the `--flake` flag to get it to actually work `nixos-rebuild switch --flake ./my-flake#nixosConfigurations.my-config`.
