### ISSUE TITLE
README example didn't work

### ISSUE THREAD

**Issue by teh** [numtide/nixos-anywhere#126]
**Describe the bug**

Example in README didn't work

**To Reproduce**

I copy-pasted the disko config which complains with 

```
error: The option `disko.devices.disk.main.content.partitions."[definition 1-entry 1]".type' does not exist. Definition values:
       - In `/nix/store/3lrc9lybsdxdwqv9fadbf0xzw40qa7j5-source/flake.nix': "partition"
```
I think it might have to be this?

```
              part-type = "primary";
```

**Expected behavior**

example works 

**System information**

nixos 22.11

**Additional context**

**Comment by Lassulus** [comment]
ah yeah I changed the disko types, will open a PR in a sec
