### ISSUE TITLE
`--extra-files` option

### ISSUE THREAD

**Issue by yellowhat** [numtide/nixos-anywhere#141]
**Describe the bug**

Hi,

I have just discovered this amazing project and triggered my interest in nixos.

I would like to read some input of the nix configuration from a file, like:

```nix
programs.bash.interactiveShellInit = builtins.readFile ./bash-config.sh;
```

But I get the error that the file cannot be found.

I have noticed that there is the option `--extra-files` but looking at the file [nixos-anywhere.sh](https://github.com/numtide/nixos-anywhere/blob/main/src/nixos-anywhere.sh) there are only 2 lines that reference it:

- [28](https://github.com/numtide/nixos-anywhere/blob/7871740187a5ede388daf110fc2ee5797c4248ad/src/nixos-anywhere.sh#LL28C1-L28C26)
- [106](https://github.com/numtide/nixos-anywhere/blob/7871740187a5ede388daf110fc2ee5797c4248ad/src/nixos-anywhere.sh#LL28C1-L28C26) 

therefore seems this option is defined but discarded.

Thanks 

**To Reproduce**

1. `programs.bash.interactiveShellInit = builtins.readFile ./bash-config.sh;`
2. `nix run github:numtide/nixos-anywhere -- --flake .#server --extra-files ./bash-config.sh --debug k8s@127.0.0.1`

**Expected behavior**

`bash-config.sh` file is available in the source

**Comment by yellowhat** [comment]
Ahhhhhhhhhh, sorry for the dumb mistake missed the "-" > "_".

May I ask what do you mean by adding a file to the flake, are you referring to the file content?

The `programs.bash.interactiveShellInit = builtins.readFile ./bash-config.sh;` is already in `flake.nix`.

Thanks

**Comment by phaer** [comment]
You are running nixos-anywhere using a flake. The relative path in your expression refers to the directory of your flake. So you could just add "bash-config.sh" to your git repository.

As that's not really related to nixos-anywhere, I'll close this issue, the official discourse and matrix channel are a better support channel for such general questions :)
