### ISSUE TITLE
Does nixos-anywhere require a single-use flake during installation?

### ISSUE THREAD

**Issue by Nairou** [numtide/nixos-anywhere#144]
I've been looking for a way to pre-plan the installation of NixOS on two of my servers with as little downtime as possible, and just discovered `nixos-anywhere` which looks promising.

One thing that confuses me though, the instructions talk about creating a flake for the target installation, which largely looks like a regular NixOS configuration, but includes `disko` partitioning info. Which makes me assume that this flake is only to be used once, to get NixOS installed, and then never again for fear of re-partitioning the drive over and over.

Is this correct? Do I need to create a minimal configuration flake to use with `nixos-anywhere` that is separate from the actual flake configuration I intend to use on the target server? Or is the intent to use a final configuration during installation, and the partition info is somehow only used once?

**Comment by phaer** [comment]
No, you can have everything in a single flake. 

Disko configuration should be included for installation only, it won't be used afterwards - expect if you explicitly generate partitioning scripts from it.

**Comment by Nairou** [comment]
> No, you can have everything in a single flake.

Thanks, good to know!

> Disko configuration should be included for installation only, it won't be used afterwards - expect if you explicitly generate partitioning scripts from it.

Can you explain what you mean by "included for installation only"? Does `nixos-rebuild` ignore it, and it's only used by the `nixos-anywhere` script? Or do you mean I need to edit that section out after installation?

**Comment by phaer** [comment]
> Does nixos-rebuild ignore it, and it's only used by the nixos-anywhere script?

Yes, with --flake, nixos-anywhere uses  nixosConfigurations.your-hostname.config.system.build.diskoScript by default. You can also pass a custom script via "-s".

No need to edit it out
