### ISSUE TITLE
Installing x86-64 system from m1 mac

### ISSUE THREAD

**Issue by micke** [numtide/nixos-anywhere#152]
**Is your feature request related to a problem? Please describe.**

Trying to use nixos-anywhere from my M1 Mac gives me the following error:

```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/nvnbh63ik024vf686qh9cz29snm1ry5l-disko.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```

I'm new to nixos but was under the impression that this would work when using `--build-on-remote`.

The command i'm running is:

```
nix run github:numtide/nixos-anywhere -- --flake .#higgins --build-on-remote root@10.0.10.8
```

With the following code: https://github.com/micke/home-cluster/tree/18255d6428e2c5e5ec562701862ff5d133f3cd3d/install

**Describe the solution you'd like**

I'd like to be able to run nixos-anywhere from my mac.

**Describe alternatives you've considered**

I've also tried using the remote builder option without any more luck:

```
nix run github:numtide/nixos-anywhere --builders "ssh://10.0.10.8?user=root" -- --flake .#higgins --build-on-remote root@10.0.10.8
```

**Additional context**

**Comment by erikkrieg** [comment]
Hey, not a maintainer here, I'm just cruising the issues. Looks like your github project that you're linking is private and not visible.

**Comment by micke** [comment]
@erikkrieg thanks for the heads up, it’s public now!

**Comment by Mic92** [comment]
I think that is actually supposed to work. @Lassulus did we regress on that?

**Comment by Mic92** [comment]
Can you add the --debug flag so we can see which nix build fails here?

**Comment by Mic92** [comment]
Potentially you also need to be a trusted nix user on your mac or else nixos-anwhere's remote builder flag won't be effective.

**Comment by domenkozar** [comment]
Wouldn't nixos-anywhere be able to do that since it has root access?

**Comment by domenkozar** [comment]
You can safeguard it:

```
nix store ping
Store URL: daemon
Version: 2.16.1
Trusted: 1
```

**Comment by Mic92** [comment]
> Wouldn't nixos-anywhere be able to do that since it has root access?

On the remote machine yes, but it also runs this locally: https://github.com/numtide/nixos-anywhere/blob/a9b9f65eba12b52037710de85c10a1740a80dcee/src/nixos-anywhere.sh#L401

**Comment by Mic92** [comment]
But if we should definitely add a check if the local user is trusted when this flag is used.

**Comment by Mic92** [comment]
@micke https://github.com/Mic92/dotfiles/blob/05c0dbc5ba882fbe4d51cffe6e124cdfcd924983/nixos/modules/nix-daemon.nix#L34 you want something like this in your /etc/nix/nix.conf for your own user.

**Comment by micke** [comment]
@Mic92 and @domenkozar Thanks guys! That seems to have done the trick!
I could now run it from my M1 mac without having to use UTM to emulate x86 :D
