### ISSUE TITLE
Installation could not be completed normally.

### ISSUE THREAD

**Issue by god464** [numtide/nixos-anywhere#170]
**Describe the bug**

Although the console print done, when I reboot the machine in virtual machine, I could not enter the system correctly. It still shows the installation interface.

**To Reproduce**
This is my shell record: https://fars.ee/t/9A05.json

**Expected behavior**

It should enter the system correction.

**System information**

My nix config

https://github.com/god464/NeoDotfile

**Comment by phaer** [comment]
This looks like you aren't using kexec where, but booted an installer on the target machine before you ran `nixos-anywhere`. Is this correct? 

If so you need to remove the installer medium (i.e. image attached to vm) yourself or configure the target machine to boot from the disk where nixos gets installed first.

If not, we'd need to check whether the machine actually uses EFI to boot, as the config wouldn't be compatible with legacy/MBR boot as far as i see from a quick glance.

**Comment by god464** [comment]
Of course I'm not using kexec. But I don't think that's the main reason because of the logs that appeared during the installation process:
```bash
File system "/dev/sda1" has wrong type for an EFI System Partition (ESP).                                               
Traceback (most recent call last):                                                                                      
  File "/nix/store/zqbxnxdp110mvq7ck614l0x2hjh18wzr-systemd-boot", line 341, in <module>                                
    main()                                                                                                              
  File "/nix/store/zqbxnxdp110mvq7ck614l0x2hjh18wzr-systemd-boot", line 258, in main                                    
    subprocess.check_call(["/nix/store/41d6dz6cj7kj52gfmbyqwhp4hkvbrmfg-systemd-253.6/bin/bootctl", "--esp-path=/boot"] 
+ bootctl_flags + ["install"])                                                                                          
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/subprocess.py", line 369, in check_ca
ll                                                                                                                      
    raise CalledProcessError(retcode, cmd)                                                                              
subprocess.CalledProcessError: Command '['/nix/store/41d6dz6cj7kj52gfmbyqwhp4hkvbrmfg-systemd-253.6/bin/bootctl', '--esp
-path=/boot', 'install']' returned non-zero exit status 1.
```
I had this same error when trying to install with only  flake + disko, and I checked to make sure the install mode was under UEFI.

**Comment by phaer** [comment]
Ah, it helps "of course" to mention the actual error instead of expecting people to skim the recording above.

> File system "/dev/sda1" has wrong type for an EFI System Partition (ESP).                                               

Which looks quite clear to me, your disko config doesn't set a "type" for the ESP partition, e.g. https://github.com/nix-community/disko/blob/4015740375676402a2ee6adebc3c30ea625b9a94/example/simple-efi.nix#L11

**Comment by god464** [comment]
It look good now. Thank you.
