### ISSUE TITLE
kexec fails on Raspberry Pi OS: missing /proc/kcore

### ISSUE THREAD

**Issue by arilotter** [numtide/nixos-anywhere#183]
**Describe the bug**

targeting a Raspberry Pi OS system with `nixos-anywhere` will fail at the kexec stage with the error
```
+ /root/kexec/kexec/kexec --load /root/kexec/kexec/bzImage --initrd=/root/kexec/kexec/initrd --no-checks --command-line init=/nix/store/SNIPPED/init console=tty0 console=ttyAMA0,115200 console=ttyS0,115200 loglevel=4
Can't open (/proc/kcore).
Warning, can't get the VA_BITS from kcore
Can't open (/proc/kcore).
```

**To Reproduce**

1. Install Raspberry Pi Linux on a Raspberry Pi
2. Try to deploy any system config to it using `nixos-anywhere`

**Expected behavior**

The deployment should succeed.

**System information**

nixos-anywhere `5cdd6d6d2633498ff65dd6b15eaec8b9b8e7a3e2`
raspberry pi os: `2023-05-03-raspios-bullseye-armhf-lite.img` (available at https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2023-05-03/2023-05-03-raspios-bullseye-armhf-lite.img.xz )

also tried after running `rpi-update` to grab latest unstable kernel.

**Additional context**
It seems that this platform *may* just be missing kcore entirely, and require a different approach.
I'm not too learned in these details, though, so could be wrong.

**Comment by Mic92** [comment]
Could be the case that raspberry pi os does not enable kexec.

I mounted the image you provided and extracted the kernel configuration from config.ko.xz using binwalk:

[config.txt](https://github.com/numtide/nixos-anywhere/files/12447672/config.txt)
