### ISSUE TITLE
filesystem mountOptions not respected during install?

### ISSUE THREAD

**Issue by sedlund** [numtide/nixos-anywhere#188]
**Describe the bug**

Using disko config to create btrfs filesystems with `mountOptions = ["compress=zstd:1]`.  Disko will create the filesystems and I presume the mount units.  I am unsure if it is disko or nixos-anywhere that then mounts the filesystems -- but whatever it is it does not use the `mountOptions`, so the system installed without compression enabled.  After reboot the mountOptions take effect as expected.

**To Reproduce**

```
            content = {
              type = "btrfs";
              extraArgs = ["-f"]; # Override existing partition
              subvolumes = {
                # Subvolume name is different from mountpoint
                "/rootfs" = {
                  mountpoint = "/";
                };
                # Subvolume name is the same as the mountpoint
                "/home" = {
                  mountOptions = ["compress=zstd:1"];
                  mountpoint = "/home";
                };
                # Sub(sub)volume doesn't need a mountpoint as its parent is mounted
                "/home/sedlund" = {};
                # Parent is not mounted so the mountpoint must be set
                "/nix" = {
                  mountOptions = ["compress=zstd:1" "noatime"];
                  mountpoint = "/nix";
                };
              }; # subvolumes
            }; # content.btrfs
          }; # content.luks

```

**Expected behavior**

I would think mountOptions should be respected, or some other mechanism provided to allow the system to be installed with compression enabled - or being new to all this I am missing something.  Any help appreciated.

**System information**

    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
    disko.url = "github:nix-community/disko";
    disko.inputs.nixpkgs.follows = "nixpkgs";

**Additional context**

**Comment by Mic92** [comment]
Disko is doing all the filesystem stuff. nixos-anywhere is just calling into it.

**Comment by Mic92** [comment]
Actually it takes mount options into account:

https://github.com/nix-community/disko/blob/4eed2457b053c4bbad7d90d2b3a1d539c2c9009c/lib/types/btrfs.nix#L115

I don't see a code path where it does use mount options.

Can you run nixos-anywhere with --debug? Than you should see all the commands from disko as well in a more verbose way.

**Comment by sedlund** [comment]
Thanks  for your help!  With `--debug` I was able to spot the problem.

The issue was that btrfs applies compression settings per device, not per subvolume.

The [example provided by disko](https://github.com/nix-community/disko/blob/master/example/btrfs-subvolumes.nix) which I was following does not apply compression `mountOptions`  to the `/rootfs` subvolume.  Since it is the first mounted, btrfs does not enable compression on the device, then subsequent `mount`s that specify enabling will silently fail to 
compression.

To resolve, add compression (same settings desired on the whole device) to the `/rootfs` subvolume in this example.
