### ISSUE TITLE
Can nixos-anywhere be used to rescue a machine, rather than formatting it?

### ISSUE THREAD

**Issue by pwaller** [numtide/nixos-anywhere#207]
**Is your feature request related to a problem? Please describe.**

Some machine providers have can boot to a predefined a rescue image, but of course I would like to use my own nixos configuration to rescue an machine if possible, because, for example, that image may not be able to access the filesystems the machine is formatted with.

**Describe the solution you'd like**

I would like to be able to use nixos-anywhere to make the (e.g. debian) machine kexec into a nixos configuration, and then handle the rescue of the system from there.

I believe nixos-anywhere already does this, however it then goes on to run nixos-install, which I don't want. So I'm currently assuming it could be made to work for my use case with only minor tweaks.

**Describe alternatives you've considered**

Right now I use a VM, passing through the underlying block devices. However, this requires that I build the VM in advance and transfer it to the target machine, which can be quite large. It would be preferable to 'fetch nixos-anywhere' and then run a command.

**Additional context**

The rescue image may not be able to access some of the filesystems on the block devices, requiring use of software provided by nix.

**Comment by phaer** [comment]
> I would like to be able to use nixos-anywhere to make the (e.g. debian) machine kexec into a nixos configuration, and then handle the rescue of the system from there.

You could build a kexec bundle of your desired configuration via https://github.com/nix-community/nixos-generators and use that, I believe?

> I believe nixos-anywhere already does this, however it then goes on to run nixos-install, which I don't want. So I'm currently assuming it could be made to work for my use case with only minor tweaks.

You wrote "into a nixos configuration" which I interpret as "into an arbitrary nixos configuration"? nixos-anywhere does not kexec into *your* NixOS configuration normally, but a generic one (from https://github.com/nix-community/nixos-generators). It only uses your nixos configuration for installation, which probably isn't what you want here

**Comment by phaer** [comment]
> That does indeed look quite useful. Pitty that the kexec functionality is currently marked as broken.

Oh, you're right that's a petty. @Lassulus started to work on that in June and asked for feedback in https://github.com/nix-community/nixos-generators/pull/261

> Happy to close this issue one if it is considered out of scope for nixos-anywhere.

I think fixing nixos-generators and continuing with that might be a better avenue here.
It seems indeed a bit out of scope as nixos-anywhere is foremost an installer and uses kexec images from https://github.com/nix-community/nixos-images by default. You could use nixos-anywhere to (re-)install via your custom kexec image after you've built it.

So I am closing this for now, but feel free to re-open :)
