### ISSUE TITLE
Installation succeeds but builds entirely wrong fstab file

### ISSUE THREAD

**Issue by solomon-b** [numtide/nixos-anywhere#210]
**Describe the bug**

I'm trying to setup a new laptop (Dell XPS 15). The installation succeeds but on boot the partition is not accessible:
```
Waiting 10 seconds for device /dev/nvme0n1p2 to appear.......... - failure
/dev/nvme0n1p2 is unavailable
```

I used a boot disk to investigate and the partition was totally fine. I mounted it and poked around and saw that the `fstab` file was totally wrong. It was identical to that of the nixos bootdisk i used during provisioning:

```
# This is a generated file.  Do not edit!
#
# To make changes, edit the fileSystems and swapDevices NixOS options
# in your /etc/nixos/configuration.nix file.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>

# Filesystems.
tmpfs / tmpfs x-initrd.mount,mode=0755 0 0
/dev/root /iso auto x-initrd.mount 0 0
/iso/nix-store.squashfs /nix/.ro-store squashfs x-initrd.mount,loop 0 0
tmpfs /nix/.rw-store tmpfs x-initrd.mount,mode=0755 0 0
overlay /nix/store overlay x-initrd.mount,lowerdir=/nix/.ro-store,upperdir=/nix/.rw-store/store,workdir=/nix/.rw-store/work 0 0


# Swap devices.
``` 

**To Reproduce**

I'm not sure. My system config uses sops-nix for secrets so it would be a pain to try to instally my config on a vm or whatever to test this. 

**Expected behavior**

**System information**

nixos 23.05

**Additional context**

This is the machine config in question: 
https://github.com/solomon-b/nixos-config/blob/main/flake.nix#L223-L241

And this is a script i use to wrap nixos-anywhere:
https://github.com/solomon-b/nixos-config/blob/main/installer/install-pc.sh#L39

**Comment by solomon-b** [comment]
Closing due to user error.

**Comment by NachoPicchu** [comment]
@solomon-b Do you happen to remember what your user error was? I'm facing the exact same issue
