### ISSUE TITLE
New project name

### ISSUE THREAD

**Issue by Mic92** [numtide/nixos-anywhere#49]
we all more or less agree that the current name is not the nicest one. This issue is about finding a new one. Make a proposal and than we do thumb up / thump down to vote for it.

**Comment by Mic92** [comment]
nixos-anywhere

**Comment by phaer** [comment]
I don't think the current one is too bad or confusing, but:

nixos-install-remote

**Comment by zimbatm** [comment]
nixos-bootstrap

**Comment by Lassulus** [comment]
nixos-infest

**Comment by Kranzes** [comment]
nixos-establish

**Comment by domenkozar** [comment]
`bootstrap-nixos`

**Comment by zimbatm** [comment]
`nixos-unattended`

Unattended installs are installations where no user interaction is needed. This is a common word in the enterprise/windows world.

**Comment by Mic92** [comment]
I would prefer if the project name was not indicating that nixos is a virus or infection. We all had enough of those the last years.

**Comment by phaer** [comment]
I think with 7 net-upvotes for `nixos-anywhere` and a tie for second place with 2 net-upvotes for `nixos-bootstrap` and `nixos-install-remote`, it seems fair to call a winner? :1st_place_medal:

**Comment by Kranzes** [comment]
`nixos-anywhere` seems good, I like the logo.

**Comment by Mic92** [comment]
done.
