### ISSUE TITLE
Allow top-level flake attributes when using `--flake`.

### ISSUE THREAD

**Issue by imsofi** [numtide/nixos-anywhere#61]
**Is your feature request related to a problem? Please describe.**

Allow looking up to top level for an attribute. Hit a failure when i attempted to use a top-level `images.hetzner-cloud-kexec` naming scheme. The configuration works correctly when moved to `nixosConfigurations`.

```
nix run github:numtide/nixos-anywhere -- root@xx.xx.xx.xx --flake .#images.hetzner-cloud-kexec
error: flake 'git+...' does not provide attribute 'packages.x86_64-linux.nixosConfigurations.images.hetzner-cloud-kexec.config.system.build.disko', 'legacyPackages.x86_64-linux.nixosConfigurations.images.hetzner-cloud-kexec.config.system.build.disko' or 'nixosConfigurations.images.hetzner-cloud-kexec.config.system.build.disko'
```

**Describe the solution you'd like**

Let `nixos-anywhere` walk all the way up to the top-level to look for an attribute to allow writing full lookups.

**Describe alternatives you've considered**

Using `nixosConfigurations`. Could work okay, but I personally do not like mixing install images and live systems. This could be solved by letting `nixos-anywhere` install full new systems at the kexec step. Unsure if there are any good reasons to seperate into a two stage deployment. (Install then a bigger configuration-install after reboot).

**Additional context**

None

**Comment by Mic92** [comment]
The current scheme follows the one of `nixos-rebuild`, I would prefer to use it this way for consistency as this allows to use the same configuration for initial installation and later for deployment. I am not quite sure why you are specifying not your final nixos configuration there but some "live" system? In any case I think you can also just have two attributes in nixosConfigurations with different names.

**Comment by imsofi** [comment]
Yeah it was primarily due to the extra dependency `disko` and worry that it could overwrite partitions if the underlying drives changed.

From a 2nd look, it seems only to generate `disko-create` and `disko-mount` commands, and not actively watch the system at boot. This should not be that big of an issue anymore.

> I am not quite sure why you are specifying not your final nixos configuration there but some "live" system?

Stems from a habit of writing up "image files" that return isos/qcow2 images. But this might be the wrong place to apply that habit now that i think about it a bit more.

**Comment by phaer** [comment]
> Stems from a habit of writing up "image files" that return isos/qcow2 images. But this might be the wrong place to apply that habit now that i think about it a bit more.

Makes sense! Just to avoid any confusion: `--flake` defines your actual live system that gets installed to disk. The "image file" containing the system that does the installation is specified with `--kexec`. Those custom images currently need to be available via HTTP during installation. 

So I believe we can close this? Feel free to re-open if not
