### ISSUE TITLE
Use/Allow system defined `ssh` over nix packaged one.

### ISSUE THREAD

**Issue by imsofi** [numtide/nixos-anywhere#62]
**Describe the bug**

When running `nixos-anywhere`, the script will use the nixpkgs version of `openssh`. This is problematic on non-NixOS based systems such as Fedora 37. Where `openssh` is packaged with extra features, leading to a crash loop due to the feature-sets clashing inside the system's packaged openssh.config files.

```
% nix run nixpkgs#openssh -- root@xx.xx.xx.xx
/etc/crypto-policies/back-ends/openssh.config: line 3: Bad configuration option: gssapikexalgorithms
/etc/crypto-policies/back-ends/openssh.config: line 7: Bad configuration option: rsaminsize
/etc/crypto-policies/back-ends/openssh.config: terminating, 2 bad configuration options
```

**To Reproduce**

1. Install an operating system such as `Fedora 37`.
2. Install nix trough the official means or through `nix-community/nix-installers`.
3. Attempt to run `nix run nixpkgs#openssh` on the system.
4. Similarly, the `nix run github:numtide/nixos-anywhere` breaks similarly due to the above package.

**Expected behavior**

It runs correctly as if it was on NixOS.

**System information**

```
Operating System: Fedora Linux 37 (Workstation Edition)
          Kernel: Linux 6.1.7-200.fc37.x86_64
    Architecture: x86-64
```

**Additional context**

None.

**Comment by imsofi** [comment]
Running the `openssh_gssapi` version also breaks, but without the gssapi related error:

```
% nix run nixpkgs#openssh_gssapi root@xx.xx.xx.xx
/etc/crypto-policies/back-ends/openssh.config: line 7: Bad configuration option: rsaminsize
/etc/crypto-policies/back-ends/openssh.config: terminating, 1 bad configuration options
```

**Comment by imsofi** [comment]
Another solution may be to upstream a fix to `nixpkgs`, but i do not know what the best approach would be to do so.

**Comment by imsofi** [comment]
In `nixpkgs`, they decided to not hard-code the ssh binary in `git`: https://github.com/NixOS/nixpkgs/issues/160527 and https://github.com/NixOS/nixpkgs/pull/166334/commits/cae8d1a2ed7ee3bd0a3f029b452ce6ef25537278

This likely also means Apple's `ssh` config is also affected by this.

A workaround I figured out under Fedora 37 using `IgnoreUnknown` can be helpful for today:

```bash
$ cat /etc/ssh/ssh_config.d/10-nixpkgs-support.conf
Match all
    IgnoreUnknown "rsaminsize,gssapikexalgorithms"
```

So the choice would be:
1. Normalize including a file similar to `/etc/ssh/ssh_config.d/10-nixpkgs-support.conf` for support.
2. Take from how [git inside nixpkgs solved this](https://github.com/NixOS/nixpkgs/pull/166334/commits/cae8d1a2ed7ee3bd0a3f029b452ce6ef25537278).
3. Take from git, but use `GIT_SSH` as the preferred binary if available.

**Comment by Mic92** [comment]
see https://github.com/numtide/nixos-anywhere/pull/66
