### ISSUE TITLE
kexec_load failed: Invalid argument

### ISSUE THREAD

**Issue by delneg** [numtide/nixos-anywhere#84]
**Describe the bug**
```
22 blocks
~/kexec/kexec/tmp.1FvK0gLD2M
+ popd
+ cat extra.gz
+ rm -r /root/kexec/kexec/tmp.1FvK0gLD2M
+ /root/kexec/kexec/kexec --load /root/kexec/kexec/bzImage --initrd=/root/kexec/kexec/initrd --command-line 'init=/nix/store/nf32aa02c3nj9qmd391vp8li1g9sazrx-nixos-system-nixos-22.11pre-git/init console=tty0 console=ttyS0,115200 nohibernate loglevel=4'
kexec_load failed: Invalid argument
entry       = 0x3ffd0760 flags = 0x3e0000
nr_segments = 5
```

**To Reproduce**

Tried to use https://github.com/tfc/nixos-anywhere-example/blob/main/single-gpt-disk-fullsize-ext4.nix with
hetzner-cloud flake on a QEMU vm

```
nix run github:numtide/nixos-anywhere -- root@1.1.1.1 --flake .#cloud-vm
```

System had not enough ram, so a swapfile was created.

Also, I'm running this command from aarch64-linux (on a mac with Rosetta enabled, previously tested with building various x86_64 systems with no issues)

**Expected behavior**

Nixos installed

**System information**

Linux v7777777.local 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Lassulus** [comment]
Afair swap files wont survive kexec so they won't help against not enough ram

**Comment by delneg** [comment]
Maybe make "swap does not count" **bold** in README :)
Closing then.
