### ISSUE TITLE
Getting this to take over a docker container with nixOS

### ISSUE THREAD

**Issue by super-secret-github-user** [numtide/nixos-anywhere#85]
**Is your feature request related to a problem? Please describe.**

I'm attempting to push nix into my org. 

We currently use coder for our development environments. We have a prototype which sets up everything we need using nix. 

Some things, like the vs-code-server, need systemd to run.

**Describe the solution you'd like**

Instead of setting everything up w systemd units and running that at startup, I figured it would be easier to manage a nixOS system.

**Describe alternatives you've considered**

systemd + oneshot units which run the nix setup - annoying to set up.
nixOS vm - at this stage the company will not support this. If I had nixOS running in a container, they would likely switch to this after a few months.

**Comment by Mic92** [comment]
No it cannot be used in docker containers. It's intended used in an environment with a kernel.
