### ISSUE TITLE
Kernel panic during install on OVH VPS

### ISSUE THREAD

**Issue by boozedog** [numtide/nixos-anywhere#92]
Using nix-anywhere to try to install on OVH VPS with 4GB of RAM running Debian 11 non-EFI.

Install seems to work fine up 'til this point:

```sh
...

+ /root/kexec/kexec/kexec --load /root/kexec/kexec/bzImage --initrd=/root/kexec/kexec/initrd --command-line 'init=/nix/store/w8x4ggsygn5g8np2gwn8i3dvhfpss9bz-nixos-system-nixos-22.11pre-git/init console=tty0 console=ttyS0,115200 nohibernate loglevel=4'
machine will boot into nixos in in 6s...
+ echo 'machine will boot into nixos in in 6s...'
+ [[ -e /dev/kmsg ]]
+ exec
```

On server console I see Kernel panic:

![Screenshot from 2023-05-04 10-29-04](https://user-images.githubusercontent.com/1410808/236251720-749b593f-1136-4eee-88b3-5d68d094c25c.png)

Any ideas? Let me know what additional details might be helpful.

cc: @tfc

**Comment by Lassulus** [comment]
Did you try it multiple times? What command did you run?

**Comment by Lassulus** [comment]
Ah probably something went wrong during the copying of the initrd to the targetsystem. We pipe it directly into tar so it could be susceptible to small network hiccups. Maybe we can make it more robust

**Comment by Mic92** [comment]
Closing for now until we have indication there is a reproducible bug we can fix.
