### ISSUE TITLE
Error during kexec: Cannot access parent directories

### ISSUE THREAD

**Issue by tfc** [numtide/nixos-anywhere#93]
**Describe the bug**

Hi, i just tried to nixos-anywhere into an installed Debian 5.10.162 on a Hetzner VM that was configured by someone else.
On Hetzner rescue systems this typically works. 

What's obviously different here is that i don't have the root password, but a normal user account with sudo-rights. 

The kexec part does not work. The machine does not come online after the kexec part, and the VM console shows this (typed it off the graphical screen):

```
[96822.464035] + nohup bash -c 'sleep 6 && \''/root/kexec/kexec/kexec/kexec'\'' -e '
[96822.517973] shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

Is it obvious to someone what happened here, by looking at this message?

**Comment by Mic92** [comment]
Did the script return an error while doing pushd?

I think I have seen some cases where the script was run by dash instead of bash.
I have started making it dash compatible here: https://github.com/nix-community/nixos-images/pull/98/files#diff-ff7df1f527ed74b8fb41cd04d80e677a371bb00bdcbeeceb7f631f4e4c5d46a2L28

**Comment by tfc** [comment]
I did not re-run the script, yet, because I don't have access to the rescue and reload interface of that VM.
The next step that I planned was building a "dry run" version of the `run` script of the kexec image download and debug that.

It's good that you point to dash... the system that I'm running on uses dash:

```
$ file /bin/sh
/bin/sh: symbolic link to dash
```

So that might be the problem, right?
Is the version that you started making dash compatible ready to try it out?

**Comment by Mic92** [comment]
> So that might be the problem, right? Is the version that you started making dash compatible ready to try it out?

After the CI succeeds, yes: https://github.com/nix-community/nixos-images/pull/98#issuecomment-1537419149

**Comment by tfc** [comment]
Ok, this seems to work now. The whole thing goes OOM, but that's a completely different topic.

Thank you for fixing this!
